"""added phone number to users

Revision ID: 243ee2beacbe
Revises: 6bc7edfa1258
Create Date: 2025-11-02 08:09:36.295822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '243ee2beacbe'
down_revision: Union[str, Sequence[str], None] = '6bc7edfa1258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('google_book_id', sa.String(), nullable=False))
    op.add_column('books', sa.Column('published_date', sa.String(), nullable=True))
    op.add_column('books', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_books_book_id'), table_name='books')
    op.create_index(op.f('ix_books_google_book_id'), 'books', ['google_book_id'], unique=True)
    op.drop_column('books', 'created at')
    op.drop_column('books', 'book_id')
    op.add_column('likes', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint('uq_user_book', 'likes', ['user_id', 'book_id'])
    op.drop_column('likes', 'created at')
    op.add_column('users', sa.Column('Name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('Phone_No', sa.String(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'created at')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('created at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'Phone_No')
    op.drop_column('users', 'Name')
    op.add_column('likes', sa.Column('created at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint('uq_user_book', 'likes', type_='unique')
    op.drop_column('likes', 'created_at')
    op.add_column('books', sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('books', sa.Column('created at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_books_google_book_id'), table_name='books')
    op.create_index(op.f('ix_books_book_id'), 'books', ['book_id'], unique=True)
    op.drop_column('books', 'created_at')
    op.drop_column('books', 'published_date')
    op.drop_column('books', 'google_book_id')
    # ### end Alembic commands ###
